package com.lw.dao;

import com.lw.dataObject.ItemStockDao;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface ItemStockDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Sep 07 11:44:56 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Sep 07 11:44:56 CST 2021
     */
    int insert(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Sep 07 11:44:56 CST 2021
     */
    int insertSelective(ItemStockDao record);

    ItemStockDao selectByItemId(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Sep 07 11:44:56 CST 2021
     */
    ItemStockDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Sep 07 11:44:56 CST 2021
     */
    int updateByPrimaryKeySelective(ItemStockDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Tue Sep 07 11:44:56 CST 2021
     */
    int updateByPrimaryKey(ItemStockDao record);

    int decreaseStock(@Param("itemId") Integer itemId, @Param("amount") Integer amount);
}