package com.lw.dao;

import com.lw.dataObject.ItemDao;
import com.lw.dataObject.PromoDao;
import com.lw.dataObject.PromoDaoKey;
import org.springframework.stereotype.Repository;

@Repository
public interface PromoDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 07 18:53:57 CST 2021
     */
    int deleteByPrimaryKey(PromoDaoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 07 18:53:57 CST 2021
     */
    int insert(PromoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 07 18:53:57 CST 2021
     */
    int insertSelective(PromoDao record);

    PromoDao selectByItemId(Integer ItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 07 18:53:57 CST 2021
     */
    PromoDao selectByPrimaryKey(PromoDaoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 07 18:53:57 CST 2021
     */
    int updateByPrimaryKeySelective(PromoDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Tue Sep 07 18:53:57 CST 2021
     */
    int updateByPrimaryKey(PromoDao record);
}