package com.lw.dao;

import com.lw.dataObject.SequenceDao;
import org.springframework.stereotype.Repository;

@Repository
public interface SequenceDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 07 16:48:08 CST 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 07 16:48:08 CST 2021
     */
    int insert(SequenceDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 07 16:48:08 CST 2021
     */
    int insertSelective(SequenceDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 07 16:48:08 CST 2021
     */
    SequenceDao selectByPrimaryKey(String name);

    SequenceDao getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 07 16:48:08 CST 2021
     */
    int updateByPrimaryKeySelective(SequenceDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Sep 07 16:48:08 CST 2021
     */
    int updateByPrimaryKey(SequenceDao record);
}