package com.lw.dao;

import com.lw.dataObject.UserPasswordDao;
import org.springframework.stereotype.Repository;

@Repository
public interface UserPasswordDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Sep 06 15:53:35 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Sep 06 15:53:35 CST 2021
     */
    int insert(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Sep 06 15:53:35 CST 2021
     */
    int insertSelective(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Sep 06 15:53:35 CST 2021
     */
    UserPasswordDao selectByPrimaryKey(Integer id);

    /**
     * 添加的根据 user_id 获取 encrypt_password的 mybatis方法
     * @param userId
     * @return
     */
    UserPasswordDao selectByUserId(Integer userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Sep 06 15:53:35 CST 2021
     */
    int updateByPrimaryKeySelective(UserPasswordDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Mon Sep 06 15:53:35 CST 2021
     */
    int updateByPrimaryKey(UserPasswordDao record);
}